### ISSUE TITLE
VoiceApi.swift error in Xcode 12

### ISSUE THREAD

**Issue by rcal42** [what3words/voice-api-ios-example#1]
Hi

Line 37 of VoiceApi.swift produces an error and will not compile in Xcode 12
Error is:
Cannot convert value of type '()?' to closure result type '()'

This seems to be related to 
https://stackoverflow.com/questions/63957997/update-to-xcode-12-cannot-convert-value-of-type-datarequest-to-closure-result
but I am not sure how to fix it

thanks

**Comment by rcal42** [comment]
ok fixed it - guess I just had to delete the "?", so 
var suggestions: ([VoiceSuggestion]) -> ()? = { _ in }
becomes
var suggestions: ([VoiceSuggestion]) -> () = { _ in }

but should still be fixed in the sample code - thanks

**Comment by dave-w3w** [comment]
Thanks for the heads up.  I have fixed this issue.
Though this is an early example of using our Voice API that we put up before we published our Swift API wrapper.
I strongly recommend that you use our Swift wrapper at: https://github.com/what3words/w3w-swift-wrapper
...and take a look at the Voice API Example in there.
